### ISSUE TITLE
Selecting OSFMount's destination

### ISSUE THREAD

**Issue by ChampionLeake** [mondul/HiyaCFW-Helper#1]
Something that I think that would be useful would be to have a feature to select the location of OSFMount itself instead of automatically doing it. It can sometimes leads to issues and there could be other ways to make the tool with without having OSFMount found at a specific destination.

**Comment by mondul** [comment]
@ChampionLeake uploaded a new release, please test if the OSFMount problem is still happening.

**Comment by ChampionLeake** [comment]
It fixed the OSFMount issue, but the screen still freezes on 
`Downloading Launcher....`

**Comment by mondul** [comment]
OK. Will close this issue and open a new one for that.
