### ISSUE TITLE
HiyaCFW Helper says "Fatcat not found. Please make sure the Windows folder is at the same Location as this Script"

### ISSUE THREAD

**Issue by Manhunter1920** [mondul/HiyaCFW-Helper#100]
So i have been trying to Install twilight menu on my Dsi (and i've also done this Before) but Whenever i Try to use HiyaCFW Helper it gives me this Error Message

     "Fatcat not found. Please make sure the Windows folder is at the same Location as this Script" 
Does anyone Know how to fix This?

**Comment by NightYoshi370** [comment]
Use 7z, not WinRAR
