### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by halfonsods** [mondul/HiyaCFW-Helper#103]
in version 3.5.1 there was a good performance the nds games ran smoothly in twilighmenu in the last version I have a lot of lag in the dsiware and in twilight menu I would appreciate a compiled version of version 3.5.1 or instructions on how to compile it

**Comment by Epicpkmn11** [comment]
That's not related to the HiyaCFW Helper, its probably an issue with your SD card, if you still need help try asking on the [DS⁽ⁱ⁾ Mode Hacking Discord server](https://discord.gg/yD3spjv)
