### ISSUE TITLE
Could not get HiyaCFW

### ISSUE THREAD

**Issue by jiahao303** [mondul/HiyaCFW-Helper#105]
I installed python through Homebrew and keep getting this error, even after running pip install certifi. How do I make sure Terminal is using the version of python installed through Homebrew?

**Comment by Epicpkmn11** [comment]
Sorry for the really late reply, but if you're still needing it, could you try the latest release? It now has a macOS zip that should include everything.

Going to close this since its probably fixed and has been nearly a month, but feel free to reopen if the new release doesn't work
