### ISSUE TITLE
HiyaCFW Helper v3.6.2 Windows version does not launch.

### ISSUE THREAD

**Issue by CommandBlock6417** [mondul/HiyaCFW-Helper#106]
I was trying to launch the latest version of HiyaCFW helper on an x64 Windows computer. First of all, I got a "suspected virus" alert from Chrome and had to use firefox to download it. Then, when I ran it my pc said it can't run this executable (there was no zip for the windows release, only an exe) and I suspect that the antivirus may have attempted to block it or something. So if possible distribute the executable compressed to avoid such issues.

**Comment by Epicpkmn11** [comment]
Compressing it doesn't help, antiviruses will still either delete the zip or delete it when you extract it. You'll need to temporarily pause your antivirus to use this, or use the Python version

**Comment by CommandBlock6417** [comment]
It wasn't blocked by the antivirus, it was blocked by Chrome upon download.

**Comment by Epicpkmn11** [comment]
Ah, I'm pretty sure that happened when it was in a zip too though, usually virus checkers scan the contents of zips... Unfortunately there's just not much that can be done to make a PyInstaller created executable not get called a virus afaik

**Comment by CommandBlock6417** [comment]
That makes sense I guess.

**Comment by CommandBlock6417** [comment]
But here's the catch: when I downloaded the second to latest version (which was an exe along with some other files inside a zip file) I got no warnings at all

**Comment by Epicpkmn11** [comment]
Ah hmm, I just added a zip of the windows version to the latest release, can you see if Chrome will let you download that? The last one also wasn't using single file mode so I can switch back to that if needed, it'd be nice if it could stay in single file mode though...

**Comment by CommandBlock6417** [comment]
Unfortunately I don't have a Windows computer. I just went to a friend's house yesterday that had a dsi and I tried it there, so I can't 100% reproduce the issue. My dad does have a laptop I can try later though.

**Comment by Epicpkmn11** [comment]
Ah, just tested on a Windows computer I've got and Chrome was fine with it in a zip so I'll just switch to that, thanks for letting me know

**Comment by CommandBlock6417** [comment]
Glad I could help.
