### ISSUE TITLE
macOS Big Sur version mismatch error

### ISSUE THREAD

**Issue by 32teeth** [mondul/HiyaCFW-Helper#113]
> macOS Big Sur version mismatch error

Users on macOS 11.1 and running [Release Version](https://github.com/mondul/HiyaCFW-Helper/releases/tag/v3.6.5) presents a ```macOS 11 or later required``` issue.

This may be an instance reference in your code where macOS > 11 and not checking for minor release

Look forward to resolution

**Comment by Epicpkmn11** [comment]
For now I'd recommend simply using the Python 3 version as I haven't gotten around to installing Big Sur on anything and it may be a while before I can 😅 

(Just install Python 3 from the installer from https://www.python.org or using [brew](https://brew.sh) with `brew install python` in the terminal, then you can run it from the terminal with `python3 [drag and drop the HiyaCFW-Helper.py file here]` or so.)

I'll try fix this soon™ (or if someone else can fix Big Sur please PR it), but it might be a bit.

**Comment by Epicpkmn11** [comment]
I think this should be fixed, it's working for me on Monterey but I don't have Big Sur to test.
