### ISSUE TITLE
V3.6.1 fat cat not found

### ISSUE THREAD

**Issue by AN1M3H** [mondul/HiyaCFW-Helper#119]
![image](https://user-images.githubusercontent.com/88211734/131263940-a7f399af-d5a1-48bb-a696-72248b282b64.jpeg)

How can I fix this?

**Comment by Epicpkmn11** [comment]
Did you extract everything in the ZIP to the same folder? There should be a `Windows` folder in the same place as the `HiyaCFW_Helper.exe`. Also make sure to actually extract the ZIP and not just run the EXE inside it.

**Comment by AN1M3H** [comment]
> Did you extract everything in the ZIP to the same folder? There should be a `Windows` folder in the same place as the `HiyaCFW_Helper.exe`. Also make sure to actually extract the ZIP and not just run the EXE inside it.

I extracted everything but there isn't a windows folder

**Comment by Epicpkmn11** [comment]
Hmm, are you sure you're downloading the latest release: https://github.com/mondul/HiyaCFW-Helper/releases/tag/v3.6.8

**Comment by AN1M3H** [comment]
> Hmm, are you sure you're downloading the latest release: https://github.com/mondul/HiyaCFW-Helper/releases/tag/v3.6.8

It worked thanks for your help
