### ISSUE TITLE
MacOS version displays black window 

### ISSUE THREAD

**Issue by gingerbeardman** [mondul/HiyaCFW-Helper#120]
MacOS version displays black window 

I am running light mode UI as you can see by the title bar.

<img width="450" alt="Screen shot 2022-05-19 at 11 25 32" src="https://user-images.githubusercontent.com/49612/169272559-f305874e-59e8-427e-aae7-d14921bdffa7.png">

**Comment by Epicpkmn11** [comment]
Should be fixed by v3.6.9, it's working for me on Monterey at least.

**Comment by gingerbeardman** [comment]
Confirmed! (though window title still says 3.6.1)

<img width="488" alt="Screen shot 2022-05-24 at 10 11 37" src="https://user-images.githubusercontent.com/49612/169995889-4f428743-1340-4136-ba7c-ce28b48e84b2.png">
