### ISSUE TITLE
Window title still says 3.6.1 in latest version

### ISSUE THREAD

**Issue by gingerbeardman** [mondul/HiyaCFW-Helper#121]
this is 3.6.9

<img width="488" alt="Screen shot 2022-05-24 at 10 11 37" src="https://user-images.githubusercontent.com/49612/169996079-6e9a0611-e904-4932-b826-3e815c2ddd13.png">

**Comment by Epicpkmn11** [comment]
Whoops, I usually have things get the version number from git at compile time so I didn't think to update the hardcoded number in this. I've bumped it in 039e365f0ca44ed4f0c31b65fa79cce0210d26d6 preemptively for the next version but I'll leave this open until the next release.

**Comment by Epicpkmn11** [comment]
Fixed with v3.6.10
