### ISSUE TITLE
ERROR: Could not get hiyaCFW

### ISSUE THREAD

**Issue by akshayans** [mondul/HiyaCFW-Helper#122]
Hello! I am getting this error while trying to install on a mac, and yes I have already installed the certificates.
The terminal outputs this: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
If you could please help, that would be great :)

**Comment by Epicpkmn11** [comment]
Try the script from here: <https://stackoverflow.com/a/44649450> (save it to a file and `python3 cert.py` or so)

I was getting the same error on one of my computers and that fixed it. It's possible running the actual script only installed them for that version of Python but maybe it's actually using the brew or system Python and this might fix it.

**Comment by akshayans** [comment]
> Try the script from here: https://stackoverflow.com/a/44649450 (save it to a file and `python3 cert.py` or so)
> 
> I was getting the same error on one of my computers and that fixed it. It's possible running the actual script only installed them for that version of Python but maybe it's actually using the brew or system Python and this might fix it.

Nope, didn't work.
