### ISSUE TITLE
Error code 1-2435-8325 with hiyaCFW Helper!!!

### ISSUE THREAD

**Issue by ant38407** [mondul/HiyaCFW-Helper#123]
I have a 128 gb sd card and I am trying to install hiya cfw with the helper. I use a dsi and hiya keeps on showing the same error message, 1-2435-8325. I reinstalled hiya cfw helper, reinstalled twilight menu, but no luck. Can somebody help me?

**Comment by mondul** [comment]
This is a NAND related error. Please check if you can access unlaunch. If you can, it's better to run TWiLightMenu from there directly, please follow [this guide](https://wiki.ds-homebrew.com/twilightmenu/installing-dsi) for that as HiyaCFW is no longer needed by it.
