### ISSUE TITLE
json/chown error (with suggested fix)

### ISSUE THREAD

**Issue by scoutchorton** [mondul/HiyaCFW-Helper#15]
I downloaded the Python 3.0.1 zip and the version 3.0.0 release and both resulted in this error on Ubuntu:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HiyaCFW_Helper.py", line 309, in get_latest_hiyacfw
    latest = jsonify(conn)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads 
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
I know Python 2.7, so I decided to research. What I found is that when `urlopen()` gets the response, it gives a file-like output. I know that you can use `file.read()` to get the output of these files. Replicating your code with the `python3` prompt in the command line, I ran this:

```
>>> from json import loads as jsonify
>>> from urllib.request import urlopen, urlretrieve
>>> conn = urlopen('https://api.github.com/repos/RocketRobz/hiyaCFW/releases/latest')
>>> latest = conn.read()
```
I was able to get the retrieved data, but the issue was it was in a byte format, not a string. According to [this article](https://stackoverflow.com/questions/4981977/how-to-handle-response-encoding-from-urllib-request-urlopen), you would be able to use `conn.read().decode('utf-8')` to get the data. I was able to run:
```
>>> from json import loads as jsonify
>>> from urllib.request import urlopen, urlretrieve
>>> conn = urlopen('https://api.github.com/repos/RocketRobz/hiyaCFW/releases/latest')
>>> latest = jsonify(conn.read().decode('utf-8'))
>>> print(latest['assets'])
```
This ran fine with no issues. Also, I used `loads` in line 1, because `json.load` will try to load a file, but won't load an encoded file. If you read the file, decode it, then use `json.loads`, it works.

Here is what I changed:
```
#Line 20 from:
from json import load as jsonify
#to:
from json import loads as jsonify

#Line 309 from:
latest = jsonify(conn)
#to:
latest = jsonify(conn.read().decode('utf-8'))

#Line 784 from:
latest = jsonify(conn)
#to:
latest = jsonify(conn.read().decode('utf-8'))
```

I ran that and was fine until I got near the end and had a bunch of `chown: changing ownership of '/media/<username>/<SD card folder>': Operation not permitted` errors.

On the lines that use `Popen([ 'chown',  ... `, maybe change it to `Popen(['sudo', 'chown', ... `. I did run the script as sudo.

**Comment by mondul** [comment]
Can you please tell me which distro are you using?

**Comment by scoutchorton** [comment]
Ubuntu 17.04 I believe. I messed with one of my files a while ago so commands like `lsb_release -a` will say Ubuntu 16.04, but doing `cat /etc/*release` will result with `DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"` and `VERSION="17.04 (Zesty Zapus)"`. Should be 17.04 though.

Also using Python 3.5.3 (in case you need it).

**Comment by mondul** [comment]
Please do: ```sudo apt update && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt-get autoremove -y``` to update your distro (might take a while). Should be 16.04 cuz 17.04 has Python 3.6.

**Comment by mondul** [comment]
Readme updated with minimal python version required. Closing...
