### ISSUE TITLE
Error: Could not get HiyaCFW

### ISSUE THREAD

**Issue by ghost** [mondul/HiyaCFW-Helper#16]
Which path should I use for installing the software and why did I become this Error?
Please help me .-.

**Comment by Gurney-Halleck** [comment]
Hello, I just created this account to report that I am receiving the exact same error when the HiyaCFW_Helper.py script is extracting HiyaCFW archive on Mac OS X 10.9.5 with Python 3.7.2 installed:

Checking NAND file...
- eMMC CID: 5DF41310D7034D303046504100001500
- Console ID: 0820202602103137

Downloading latest HiyaCFW release...
- Extracting HiyaCFW archive...
ERROR: Could not get HiyaCFW

**Comment by mondul** [comment]
> Which path should I use for installing the software and why did I become this Error?
> Please help me .-.

Which OS are you using?

**Comment by nmcc1212** [comment]
same error, mac os running newest python as of 7th March 2019

**Comment by mondul** [comment]
Was it installed via Homebrew?

**Comment by nmcc1212** [comment]
no

**Comment by nmcc1212** [comment]
python you mean?

**Comment by nmcc1212** [comment]
and i ran the install certificates command

**Comment by nmcc1212** [comment]
in IDLE it also says

> [Errno 2] No such file or directory: 'Darwin/7za': 'Darwin/7za'

**Comment by mondul** [comment]
Replace the script with the one with the latest commit and run it from the terminal. Let me know if that works for you.

**Comment by mondul** [comment]
Ran from idle instead of terminal. Closing...
