### ISSUE TITLE
Could Not Execute Darwin / 7za on macOS

### ISSUE THREAD

**Issue by tealra1n** [mondul/HiyaCFW-Helper#18]
When trying to run this tool on macOS, I get:

Extracting HiyaCFW archive...
ERROR: Could not execute Darwin/7za

I am running macOS Mojave with the latest version of Python 3.

**Comment by mondul** [comment]
Does the 7za binary run directly? I mean, when you are at the helper's folder and run ```Darwin/7za```does it gives you any output?

**Comment by tealra1n** [comment]
Yes, it gives me a list of commands.

**Comment by tealra1n** [comment]
*I should also point out that when running HiyaCFW Helper, in the Terminal window where I executed the Python script, I get:

objc[786]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/FinderKit (0x11a80b210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1229dfdc8). One of the two will be used. Which one is undefined.

**Comment by mondul** [comment]
That warning is normal for tkinter apps. Please run a ```brew upgrade``` and try again. Meanwhile I'll update the script for printing the exception errors to the console.

**Comment by tealra1n** [comment]
Oh, and I also get "Error, Could not get HiyaCFW" when it tries to download the latest HiyaCFW release.

**Comment by mondul** [comment]
Replace the .py file with [this one](https://raw.githubusercontent.com/mondul/HiyaCFW-Helper/master/HiyaCFW_Helper.py) and tell me which errors you get.

**Comment by tealra1n** [comment]
How do I download that?

**Comment by tealra1n** [comment]
Nevermind, found it

**Comment by tealra1n** [comment]
OK, In the app I got "ERROR: Could not get HiyaCFW" and in the console, I got:

<urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:646)>

**Comment by mondul** [comment]
OK, to avoid that TLSV1_ALERT_PROTOCOL_VERSION error you must install openssh via homebrew.

**Comment by tealra1n** [comment]
I installed openssh via homebrew and tried running it but I still get the same error.

**Comment by mondul** [comment]
Was your python installed via Homebrew?

**Comment by SConaway** [comment]
You need to `cd` into the helper's folder.

**Comment by mondul** [comment]
Not a helper's issue. Closing...
