### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hecmac** [mondul/HiyaCFW-Helper#2]
hi I get 
DistutilsFileError: could not delete 'out\title\00030017\484e4155\content\title.tmd': Access is denied 
on 64bit version, pretty sure this is just me, but ive checked permissions on files and it all looks fine, so is there any other way to solve this?thanks in advance!

**Comment by mondul** [comment]
Hi, in which step are you getting that error? I'm pretty sure I'm not requesting that file to be deleted.

**Comment by Hecmac** [comment]
Sorry for the late reply I don't check email often, it's when I'm creating
the files after the cmd window says copying files to out  file, the error
comes up in the cmd window, then it just stops ( doesn't freeze though).
I've tried it with multiple PC's and error occurs on both of them. If none
else has this problem then it's probably just me doing something wrong.

**Comment by mondul** [comment]
Can you 7zip and upload your nand dump to google drive and share the link?

**Comment by Hecmac** [comment]
https://drive.google.com/open?id=1XphCPfIoWCVWGesdiDdN5LoiDqu2vre5
also my region is Aus.

**Comment by mondul** [comment]
Here's my output log with your NAND:
`Checking NAND file...
- eMMC CID: CB7F751C0A034D303046504100001500
- Console ID: 08A1942716114110

Downloading and extracting latest HiyaCFW release...

Extracting ARM7/ARM9 BIOS from NAND...
- arm7.bin SHA1:
  67BA0E54CE49517D03AE05202B4E810AE5BCF2A6
- arm9.bin SHA1:
  A20505D56E5E280E97FA8912F8E90446991689F4

Patching ARM7/ARM9 BIOS...
- Patched arm7.bin SHA1:
  EB9C4F6E740382BADA618A20C1E18529DB641D58
- Patched arm9.bin SHA1:
  76E0A55E6A016EF638119E1129124DB4565E69E0

Prepending data to ARM9 BIOS...
- Prepended arm9.bin SHA1:
  E036465899CB4DC124AF3929BE07B4573B563249

Generating new bootloader...
- bootloader.nds SHA1:
  B654E62A044282BF60860566BEC1BE254B2336AE

Decrypting NAND...

Mounting decrypted NAND...
- Mounted raw disk on /dev/disk2
- Mounted volume on /Volumes/Untitled

Extracting files from NAND...

Unmounting NAND...

Copying HiyaCFW files...

Downloading launcher...
- Detected AUS console NAND dump
- Downloading ticket...
- Downloading TMD...
  - Expected launcher SHA1:
    8F79C6C1442D3E33D211454EC92BBE42C94A599D
- Downloading encrypted content...
- Decrypting content...
- Saving 00000002.app...

Decrypting launcher...
- Decrypted launcher SHA1:
  8EF52600DA049917DCC232D5C5248419018454BF

Patching launcher...
- Patched launcher SHA1:
  88C556B1BD7B01CE5B08ED727FCDF7B19200562A

Downloading and extracting latest
TWiLight Menu++ release...

Copying TWiLight Menu++ files...

Cleaning...

Done!
Move the contents of the out folder to your DSi's
SD card
`

Here's the [output folder for your NAND](https://drive.google.com/open?id=1gzaxRy3xNn500Sf0pJpHbi3eUUkFUws4), remember after copying its content to the SD card to set the shared/TWLCFG*.dat files as read-only.

Please test it on your console and let me know if it works.

**Comment by Hecmac** [comment]
Thanks a lot!
