### ISSUE TITLE
Error: Could not get HiyaCFW.

### ISSUE THREAD

**Issue by Dragowolf33** [mondul/HiyaCFW-Helper#20]
So I got version 3.0.2 but it still says that it can't find HiyaCFW. Any solutions?

**Comment by Dragowolf33** [comment]
I'm also using the .exe version btw.

**Comment by Dragowolf33** [comment]
Never mind... All I needed to do was to have the Windows folder as well!

**Comment by mondul** [comment]
Seems to be solved, closing issue
