### ISSUE TITLE
I need help...

### ISSUE THREAD

**Issue by JoseTheNiceGuy** [mondul/HiyaCFW-Helper#22]
So I was trying to use HiyaCFW Helper but, It says can't find Python37.dll, is there a way to fix this.

**Comment by mondul** [comment]
It's included in the bundled exe for Windows.

**Comment by JoseTheNiceGuy** [comment]
ok thanks.

**Comment by JoseTheNiceGuy** [comment]
I'm back with another problem, It says mount failed, what should I mount on OSFMount?

**Comment by mondul** [comment]
May I know which Windows version are you using?

**Comment by JoseTheNiceGuy** [comment]
Windows 7 x64

**Comment by JoseTheNiceGuy** [comment]
That's what windows version I'm using

**Comment by mondul** [comment]
Do you have the [KB3033929](https://www.microsoft.com/en-us/download/details.aspx?id=46148) and [KB2921916](https://support.microsoft.com/en-us/kb/3033929) updates installed?

**Comment by JoseTheNiceGuy** [comment]
I might have them installed

**Comment by JoseTheNiceGuy** [comment]
But I don't know what to mount on OSFMount to make it work

**Comment by mondul** [comment]
If OSFMount fails to mount the decrypted NAND on Windows 7 you might not have those updates installed. Please run Windows Update to get them and try again.

**Comment by JoseTheNiceGuy** [comment]
I now have to update installed, what do I do now

**Comment by JoseTheNiceGuy** [comment]
It still says mounting failed, even though I installed the update

**Comment by mondul** [comment]
OSFMount no longer needed by the helper. Closing...
