### ISSUE TITLE
I need help with an error.

### ISSUE THREAD

**Issue by yukinoshingun** [mondul/HiyaCFW-Helper#24]
Whenever I start up HiyaCFW on my Ds it says "Erorr! Failed to read Launcher's title.tmd". Is there any posssible fix?

**Comment by mondul** [comment]
Check if the file ```title/00030017/484e41xx/content/title.tmd``` in your SD card is 520 bytes long

**Comment by mondul** [comment]
Not a helper's issue. Closing...
