### ISSUE TITLE
Can't run on Windows 10

### ISSUE THREAD

**Issue by coezo** [mondul/HiyaCFW-Helper#25]
I'm on Windows 10, and downloaded the 64bit version of the Helper. When I run HiyaCFW_Helper.exe, it doesn't do anything. I have a SSD and a HD. In both drives, it does that.

I could run it on Windows in Safe Mode, but I got the "ERROR: Mounter failed" even with OSFMount open (maybe related to safe mode as when I try to manually mount it, it gives me an error: service can't be shared in safe mode).

Tried to download the 32bit version, and it opens a CMD window, but fails because the architecture is not compatible.

Tried my mother's and my sister's laptop, same thing happens. Tried with the version 2.9.9.5 as well, same thing.

**Comment by mondul** [comment]
Some antivirus software does not trust python packaged executables. You can try using the python version directly.

**Comment by mondul** [comment]
Not a helper's issue. Closing...
