### ISSUE TITLE
TWLtool dissapears

### ISSUE THREAD

**Issue by blugru** [mondul/HiyaCFW-Helper#26]
When attempting to do this on my windows ten, I get this error ERROR: could not execute windows\twltool. I try copying and pasting it into the Windows folder for HiyaCFWHelper, but whenever I use the application it gives me the ERROR: could not execute windows\twltool and then deletes the twltool file.

**Comment by mondul** [comment]
Check your antivirus log to see why it's being deleted. If possible attach a screenshot of that.

**Comment by mondul** [comment]
Can't replicate. Closing...
