### ISSUE TITLE
Nintendo DSi says "an error has occured"

### ISSUE THREAD

**Issue by crensyhanilas** [mondul/HiyaCFW-Helper#27]
Reply Me Please.

**Comment by mondul** [comment]
Happens when your SD card is larger than 2GB.

**Comment by crensyhanilas** [comment]
how to fix this error "an error has occurred"

Reply for Step 1, 2 and 3.

**Comment by mondul** [comment]
Please assure your SD card is no larger than 2GB and is empty before using the helper. For now do not use the install twilight option as it's broken for now and the code needs to be updated for it to work. I already made the change but I have been unable to create a proper release for it.

**Comment by mondul** [comment]
Not a helper issue. Closing...
