### ISSUE TITLE
Could not get HiyaCFW

### ISSUE THREAD

**Issue by benc4** [mondul/HiyaCFW-Helper#30]
I have tried so many ways on my macbook pro running OSX El Capitan to get hiya and it’s just not working, I always get the “could not get hiya”error. I have tried every fix on this page and more. If you could use my backup to make the files that would be very much appreciated.

**Comment by benc4** [comment]
https://drive.google.com/file/d/1QRnQsclsqd24xkkGuvUkWW66PKGYvoDo/view?usp=sharing here is the link

**Comment by R4dioB0t** [comment]
I had this same issue. I fixed mine by going to Applications > Python 3.(Whatever) and then running Install Certificates.command (This is in finder by the way)
Hopefully, this fixes your problem.

**Comment by mondul** [comment]
Please use the Homebrew-installed python 3, I don't support any other python installations.

@benc4 Here's your zip to be extracted to the SD. Remember to set the files in the shared1 folder as read-only (mark them as locked)

https://drive.google.com/open?id=1zoNJ7Ks5fikbdI53DDrdvArLa-bn9pN0
