### ISSUE TITLE
Helper hangs at "Downloading latest HiyaCFW release..."

### ISSUE THREAD

**Issue by virtualsucks** [mondul/HiyaCFW-Helper#31]
The python script ends up hanging at "Downloading latest HiyaCFW release.." when trying to install. I check the errors in my terminal and it returns a `TypeError: the JSON object must be str, not 'bytes'`

Is it doing its thing or is it not installing the release?

**Comment by mondul** [comment]
Which OS are you using?

**Comment by virtualsucks** [comment]
Debian 9.8, Python 3.5
I just had to update python

Sorry :/
