### ISSUE TITLE
ERROR: Could not get HiyaCFW

### ISSUE THREAD

**Issue by staggerlee44** [mondul/HiyaCFW-Helper#32]
Running osx 10.11.6 and python 3.7.3 I have run the Install Certificates.command

Loader outputs this message:

Checking NAND file...
- eMMC CID: 8DEFAF18B73257373136354D00011500
- Console ID: 0820215007123126

Preparing HiyaCFW...
- Extracting HiyaCFW archive...
ERROR: Could not get HiyaCFW

**Comment by mondul** [comment]
Run it through the terminal and please use the homebrew-installed python3. I don't recommend using the pyhon.app because of these problems
