### ISSUE TITLE
bootloader.nds not found! Glitches!

### ISSUE THREAD

**Issue by crensyhanilas** [mondul/HiyaCFW-Helper#34]
![20190426_132821](https://user-images.githubusercontent.com/37714264/56804834-50325580-6827-11e9-8687-9bbd2e92319d.jpg)

**Comment by crensyhanilas** [comment]
This is a kernel panic. How do i fix it?

**Comment by mondul** [comment]
Try with a SD card or format it and check it for errors before running the helper

**Comment by mondul** [comment]
Not a helper's issue. Closing...
