### ISSUE TITLE
Error: Could not get HiyaCFW

### ISSUE THREAD

**Issue by sven200gaming** [mondul/HiyaCFW-Helper#37]
![Schermafbeelding 2019-05-04 om 19 55 45](https://user-images.githubusercontent.com/50273116/57182989-c299da00-6ea6-11e9-83de-3cadf8b10058.png)
![Schermafbeelding 2019-05-04 om 19 56 41](https://user-images.githubusercontent.com/50273116/57182991-c4fc3400-6ea6-11e9-8134-3ed845dfdc0e.png)

**Comment by sven200gaming** [comment]
and also i dont know how i can get the homebrew python

**Comment by lordfriky** [comment]
For those who are wondering, this fixed my problem
```
cd /Applications/Python\ 3.7/
./Install\ Certificates.command
```
