### ISSUE TITLE
ERROR: Darwin/7za not found and Coud not get HiyaCFW

### ISSUE THREAD

**Issue by Roiboz** [mondul/HiyaCFW-Helper#38]
Hi, well everything went pretty well at the beginning until I download the HiyaCFW-Helper-v3.0.2-Python3 (rename it to HiyaCFW-Helper1). I am doing this on Mac OSX 10.9.4. I already installed python by Homebrew using Terminal. I open up the HiyaCFW_Helper.py (it opens on IDLE 3) and click on "Run" and "Run Module", then 
<img width="439" alt="Captura de pantalla 2019-05-04 a la(s) 23 25 16" src="https://user-images.githubusercontent.com/50283447/57188418-df90d600-6ec3-11e9-9e8a-44bcad6aae3e.png">
that window opens up. I select my SD Card with the "nand.bin" file, I also select the option to "install latest TWiLight Menu++ on custom firmware". Then I receive this error 
<img width="382" alt="Captura de pantalla 2019-05-04 a la(s) 23 06 10" src="https://user-images.githubusercontent.com/50283447/57188460-b6bd1080-6ec4-11e9-84e4-9d3920cc7922.png">
And at the same time this one 
<img width="566" alt="Captura de pantalla 2019-05-04 a la(s) 23 08 51" src="https://user-images.githubusercontent.com/50283447/57188503-7e6a0200-6ec5-11e9-897c-743d12579ada.png">
I dont know what to do. Some times i get "Extractor Failed" and a file pops out 
<img width="590" alt="Captura de pantalla 2019-05-04 a la(s) 23 38 10" src="https://user-images.githubusercontent.com/50283447/57188514-ae190a00-6ec5-11e9-982a-af6c04671425.png">
The .7z file And inside of that one there are 3 folders. There isnt a tutorial about those 3 folders so I hope someone can help me.
<img width="591" alt="Captura de pantalla 2019-05-04 a la(s) 23 39 04" src="https://user-images.githubusercontent.com/50283447/57188525-e02a6c00-6ec5-11e9-9143-c43ce64d7276.png">

I would appreciate if someone helps me! Thanks!

**Comment by mondul** [comment]
Run it from the terminal as instructed on the readme

**Comment by mondul** [comment]
Ran from idle instead of terminal. Closing...
