### ISSUE TITLE
Detected as potential virus // trojan

### ISSUE THREAD

**Issue by BlockTheVillager** [mondul/HiyaCFW-Helper#4]
1 or more files are detected as viruses in the .zip

**Comment by mondul** [comment]
Could you please be more specific?

**Comment by jerbear64** [comment]
PyInstaller binaries tend to be flagged as viruses by antivirus software. This is a false positive and is safe to ignore.

If you're paranoid, you could always run the Python file directly.

**Comment by BlockTheVillager** [comment]
so the windows 64 exe does that?

**Comment by BlockTheVillager** [comment]
i guess ill install python 2.0 and run the python version

**Comment by mondul** [comment]
Someone told me that on Windows 10 the .exe got blocked by the SmartScreen filter but didn't get any virus alert from Windows Defender.

Scanned the three ZIP releases with [Kaspersky](https://virusdesk.kaspersky.com) and all were clean.

Closing ticket.
