### ISSUE TITLE
Open ERROR: Can not open the file as [FAT] archive

### ISSUE THREAD

**Issue by jbuug** [mondul/HiyaCFW-Helper#40]
Title is what is says when i try to use this tool

**Comment by Kodtiz3D** [comment]
I also get this error, in both the Heleper and the file manager for 7zip.
It does mount properly using OSFMount 2.0.1001 so it might be 7zip not supporting this specific FAT image.

**Comment by Kodtiz3D** [comment]
It seems I had 7zip version 18.1 and updated to 19.0. After running the Helper again it works properly. You are probably using an outdated 7zip version and should update to latest 7zip.

**Comment by jbuug** [comment]
Problem Solved, Thanks Kodtiz3D

**Comment by mondul** [comment]
Added 7-Zip version requirements to readme. Closing...
