### ISSUE TITLE
Helper fails with a FW 1.4U NAND dump

### ISSUE THREAD

**Issue by Kodtiz3D** [mondul/HiyaCFW-Helper#41]
I get the following error in the Helper cmd window
```Exception in thread Thread-10:
Traceback (most recent call last):
  File "shutil.py", line 563, in move
FileExistsError: [WinError 183] Cannot create a file when that file already exists: '00000002.app' -> 'E:/emulation/noSgba/tmp/iwgftu\\title\\00030017\\484e4145\\content\\00000002.app'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "HiyaCFW_Helper.py", line 817, in install_hiyacfw
    ['browser_download_url']) as src, open(filename, 'wb') as dst:
  File "shutil.py", line 577, in move
  File "shutil.py", line 263, in copy2
  File "shutil.py", line 121, in copyfile
PermissionError: [Errno 13] Permission denied: 'E:/emulation/noSgba/tmp/iwgftu\\title\\00030017\\484e4145\\content\\00000002.app'
```
The file that the Helper is copying is the patched Launcher on FW 1.4, although my NAND dump is already at FW 1.4 denoted by the Launcher filename of `00000002.app`. 
Maybe adding FW 1.4 detection in the script will help, or simply deleting/renaming `00000002.app` if it already exists in the extracted NAND dump.

**Comment by mondul** [comment]
Can you please upload your dump to Google Drive and share the link with me? Thanks

**Comment by Kodtiz3D** [comment]
I don't think that's necessary as it's an existing file conflict which seems to be an easy fix. Unless it's the second error is looking fishy.
And sending NAND files is likely against GitHub's and Google's ToS, distributing NANDs is general piracy and copyright infringement to Nintendo and I'm not for piracy.

**Comment by Miggas** [comment]
Did you fix it?
And can you tell how you did it?
I'm having the same exact problem with the same file.

**Comment by Kodtiz3D** [comment]
Yes.
An alternative method I used which I made a copy of my NAND dump, decrypted it, deleted `00000002.app` from `title\00030017\484e41XX\content\`, and then encrypted the backup copy to use in the Helper.
The (de/en)cryption process I used twltool by WinterMute https://github.com/WinterMute/twltool with the following in cmd `twltool nandcrypt --in DSi-1.mmc --out DSi-1_dec.mmc` . I mounted the NAND with OSFMount 2.0.1001 but the latest release (3.0.1004 as of writing) should work as well. 7zip can't be used for this as for some reason the backup is read only unless bypassed with something like OSFMount. 

The simplest way to fix it script side I think is to delete or rename the pre-existing Launcher in the output if it conflicts with HiyaCFW's patched one. But a slightly more complex way is to kind of detect the Launcher version by reading the Launcher's filename. `00000002.app` for FW 1.4 or `00000007.app` for FW 1.4.5 for example. 1.3U might be `00000000.app` or `00000001.app` but I don't know which one. Or by using a similar detection noted before you can check the version data's filename at `title\0003000f\484e4cXX\content\`. `00000004.app` for 1.4 or `00000009.app` for 1.4.5. Again, 1.3U might be `00000003.app` as described here http://dsibrew.org/wiki/Title_list#United_States_2. Or from reading the version directly from the version data's `.app` at hex offset `0x1B34`-`0x1B3E`. There's empty bytes between the text though so a bit of formatting would be needed for that. Or maybe have some or all of the ways to detect FW version for some error checking and sanity checks. 

Either way, however it gets solved is fine by me.
