### ISSUE TITLE
No$GBA footer not found

### ISSUE THREAD

**Issue by AzureKaos** [mondul/HiyaCFW-Helper#43]
Checking NAND file...
ERROR: No$GBA footer not found
![image](https://user-images.githubusercontent.com/45879948/58284769-c6bc6780-7d81-11e9-85ea-58a91c13509b.png)
when putting the nand in hiyacfw, give start and select an output folder, it shows this error

Edit: It looks like fwtools is not creating the NO$GBA Footer
![image](https://user-images.githubusercontent.com/45879948/58375168-77ae3800-7f23-11e9-854b-d5bfd7b5990c.png)

**Comment by mondul** [comment]
You can avoid dumping the NAND again just running fwtool and using the helper to add the footer with the consoleId and cId values it shows. Closing...
