### ISSUE TITLE
HiyaCFW Helper <certificate verify failed: unable to take local issuer certificate 

### ISSUE THREAD

**Issue by Devripe** [mondul/HiyaCFW-Helper#45]
Got this error when trying to use the Helper : HiyaCFW Helper 
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to take local issuer certificate (_ssl.c:1056)>
What am I doing wrong or how to fix that? 
I followed all the steps from the guide and used last releases....

**Comment by mondul** [comment]
Which OS?

**Comment by Devripe** [comment]
1.4.5E but after a few tries managed to get it work. Now the CFW and twilight menu++ work fine. Only question I have is, how can I turn off the WiFi? when I choose from unlaunch to load directly twilight menu++ when power on (no button pressed) WiFi remains on. If I choose loading first HiyaCFW, WiFi won't be on unless I turn it on.
Also can I use and R4 card (with 32gb microsd) and filled up with games and stuff but run the CFW and twilight menu from the SD card as it is in the moment? 
P. S. Can you please recommend me Web browser for download? I try to run Nintendo ds browser from the SD card but no luck. Screens remain white....

Thank you

**Comment by mondul** [comment]
WiFi doesn't need to be turned off, it's not connected all the time, only when needed so doesn't draw much power from the DSi.
You can use the custom firmware together with the flashcart as they are two separate things.
Don't know any other web browser for the DSi.

Closing...
