### ISSUE TITLE
ERROR: 0.fat

### ISSUE THREAD

**Issue by Vykonaut** [mondul/HiyaCFW-Helper#47]
![Untitled](https://user-images.githubusercontent.com/51265488/58749050-8496d280-84b3-11e9-9b49-09a6f2fc7966.png)

The error appears during installation of HiyaCFW taken from NAND. No files were added to the SD card afterwards. The DSi version involved is 1.4.5U.

**Comment by Techokami** [comment]
I am having this issue myself as well. How did you fix the issue @Vykonaut so that others with the same problem can solve it, too?

**Comment by Vykonaut** [comment]
Install the latest version of 7zip (7zip.org)
