### ISSUE TITLE
Exception when extracting Twilight Menu

### ISSUE THREAD

**Issue by duhow** [mondul/HiyaCFW-Helper#50]
Error when extracting Nand dump with TwiLight Menu at the SD card directly using Python / Linux.

```
Extracting /shared1/TWLCFG0.dat to /media/duhow/DATOS/shared1/TWLCFG0.dat
Extracting /shared1/TWLCFG1.dat to /media/duhow/DATOS/shared1/TWLCFG1.dat
Extracting /shared2/launcher/wrap.bin to /media/duhow/DATOS/shared2/launcher/wrap.bin
Extracting /shared2/0000 to /media/duhow/DATOS/shared2/0000
Exception in thread Thread-12:                                          
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
OSError: [Errno 22] Invalid argument: '/media/duhow/DATOS/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "HiyaCFW_Helper.py", line 733, in install_twilight
    copy_tree('_nds', path.join(self.sd_path, '_nds'))
  File "/usr/lib/python3.7/distutils/dir_util.py", line 172, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.7/distutils/dir_util.py", line 172, in copy_tree
    verbose=verbose, dry_run=dry_run))
  File "/usr/lib/python3.7/distutils/dir_util.py", line 172, in copy_tree
    verbose=verbose, dry_run=dry_run))
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.7/distutils/dir_util.py", line 176, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/lib/python3.7/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create '/media/duhow/DATOS/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp': Invalid argument
```

**Comment by kion-dgl** [comment]
I guess i'm having the same issue 

```  File "/usr/lib/python3.7/distutils/dir_util.py", line 176, in copy_tree
    dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/lib/python3.7/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create '/media/kion/9016-4EF8/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp': Invalid argument
```

**Comment by mondul** [comment]
Which Linux distro do you have?

**Comment by kion-dgl** [comment]
I should have probably included that in the previous post. I'm running debian 10, with python 3 version 3.7.3. The GUI is able to run through most of the install. It looks like if you have the "Install Latest Twilight Menu++ on custom firmware" box checked, the install_twilight function gets executed, and something inside the copy_tree call has a bad path.

could not create '/media/kion/9016-4EF8/_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers**\u**dca0bak.bmp': Invalid argument

**Comment by kerobaros** [comment]
I have the same issue here, running Arch Linux. Looks like there's a weird unicode character in one of the .bmp files. Fixed it by adding the following line to the install_twilight function, right before the copy_tree commands:

`        rename('_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers\udca0bak.bmp',
                  '_nds/TWiLightMenu/akmenu/themes/Ds Menu/calendar/clock_numbers bak.bmp')`

**Comment by mondul** [comment]
That change might break the acekard theme.

**Comment by rebeltaz** [comment]
Same issue here... Ubuntu 18.04. Before I found this, I posted my troubles on GBATemp here - https://gbatemp.net/threads/release-multi-platform-gui-hiyacfw-helper.518306/page-7#post-8677634

**Comment by jaragunde** [comment]
Hi, any news on this? Does it actually break the acekard theme, as suggested?

**Comment by jaragunde** [comment]
The workaround didn't work for me, apparently there isn't a file with that name in the origin (weird!). I worked it around by removing the `calendar` directory altogether and copying it manually later.

**Comment by mondul** [comment]
Acekard theme seems to have been fixed for a while now, closing ticket
