### ISSUE TITLE
ERROR: Could not get HiyaCFW

### ISSUE THREAD

**Issue by skassandra** [mondul/HiyaCFW-Helper#51]
On version 3.3 (Python)

**Comment by mondul** [comment]
Update to 3.7

**Comment by skassandra** [comment]
i'm on python 3.7, i'm using the HiyaCFW 3.3

**Comment by mondul** [comment]
Are you on Linux or MacOS?

**Comment by skassandra** [comment]
MacOS

**Comment by skassandra** [comment]
I tried earlier versions of Hiya, it starts but there are other problems (something about invalid directory for DSi Ware JAP)

**Comment by mondul** [comment]
Did you install python via homebrew? If not, did you run `Install Certificates.command`?

**Comment by skassandra** [comment]
i installed it from the python website

**Comment by mondul** [comment]
Run that command from `Applications` > `Python 3.7` as stated on the README. Closing...

**Comment by skassandra** [comment]
thank you!

**Comment by mondul** [comment]
You're welcome.

**Comment by maiz00** [comment]
Hi, i'm having the same issue.
Python3 install thru homebrew.
