### ISSUE TITLE
Cannot Find hiyaCFW/ No Such File or Directory: hiyaCFW.7z - WINDOWS 10

### ISSUE THREAD

**Issue by blushft3264** [mondul/HiyaCFW-Helper#52]
When I try to start to install the latest twilight menu i get an error message saying it can't find the 7 zip file "hiyaCFW.7z" and that there basically isn't a such thing.

**Comment by malek78i** [comment]
Is HiyaCFW.7z in the directory, where the Helper is?

**Comment by blushft3264** [comment]
All I see in the dire tory is the helper and a folder entitled windows and inside that folder is a tool exe file. But no hiyacfw.7z I have searched for it with the start menu and everything, thinking maybe it's in the wrong place. But it's just flat out not there. What am I missing. I've got all the steps in place and when I run the loader, it says it can't find the file. That's the only place it stops me. Once I get that hiyacfw.7z I can go through with this the rest of the way.

**Comment by mondul** [comment]
Try not to put the NAND file in a route with special characters or too long. Put it in C:\NAND\ or something like that

**Comment by blushft3264** [comment]
In the status window for the helper it says Downloading latest Hiyacfw release...
ERROR: Could not get HiyaCFW

And in the console:
[Errno 2] Nosuch file or directory: 'HiyaCFW.7z'

Not sure what I did wrong here. Went step by step and didn't use any crazy folder names with any odd characters.

**Comment by blushft3264** [comment]
> Is HiyaCFW.7z in the directory, where the Helper is?
 No, I don't believe so. I feel like if it was, my pc would find it instead of telling me there's no such file or directory.

**Comment by mondul** [comment]
By any chances do you have any antivirus software? If you do, can you check its logs to see if it's deleting the downloaded HiyaCFW.7z?

**Comment by blushft3264** [comment]
I turned off my antivirus software just in case that's what the issue was and it wasn't that, either. I am not sure where to look for logs to see if its been deleting it or not. Is there somewhere where i can just redownload the file and start over or is there some way to fix this?

**Comment by mondul** [comment]
Put it in the same folder as the helper

https://github.com/RocketRobz/hiyaCFW/releases/download/v1.3.2/HiyaCFW.7z

**Comment by blushft3264** [comment]
now, it is saying extractor failed. ugh.

**Comment by blushft3264** [comment]
Opening HiyaCFW Helper...
Initializing GUI...
Searching for 7-Zip in the Windows registry...
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\banner.bin
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\bootloader arm7 patch.ips
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\bootloader arm9 append to start.bin
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\bootloader arm9 patch.ips
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\header.bin
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\make bootloader nds.bat
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader update.ips
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\v1.4 Launcher (00000002.app) (JAP-KOR) patch.ips
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\v1.4 Launcher (00000002.app) patch.ips
ERROR: Can not open output file : The system cannot find the path specified. : .\for SDNAND SD card\title\00030017\484e4145\content\title.tmd
ERROR: Can not open output file : The system cannot find the path specified. : .\for SDNAND SD card\title\00030017\484e414a\content\title.tmd
ERROR: Can not open output file : The system cannot find the path specified. : .\for SDNAND SD card\title\00030017\484e4150\content\title.tmd
ERROR: Can not open output file : The system cannot find the path specified. : .\for SDNAND SD card\title\00030017\484e4155\content\title.tmd
ERROR: Can not open output file : The system cannot find the path specified. : .\for SDNAND SD card\hiya.dsi
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\bootloader files\ndstool.exe
ERROR: Can not open output file : The system cannot find the path specified. : .\for PC\twltool.exe
  

this is what i get.

i even ran as admin

**Comment by blushft3264** [comment]
did i say/do something wrong? lol

**Comment by mondul** [comment]
It seems you are using the helper inside a read-only folder

**Comment by mondul** [comment]
No follow up from reporter, closing ticket
