### ISSUE TITLE
'Could not open the file nand.bin'

### ISSUE THREAD

**Issue by BigTigerM** [mondul/HiyaCFW-Helper#53]
Notes to keep in mind:
- Latest version of Windows, 7z and HiyaCFW installed
- I'm new to all of this

Alright, so.
I successfully download HiyaCFW. I open it up, no problems there. Click the three dots, and open the nand.bin file. Now its in the thin rectangular box, and I press 'START'. 
Then a pop-up tells me to find an SD card path / output folder, etc. I click Ok, and brings me to another pop-up so I can select a folder. So I select the SD card, and...
A pop-up saying status appears: 
**Checking NAND file...
ERROR: Could not open the file nand.bin**
The only other thing I can do is close the pop-up, or minimize it. Thats it.
I've tried making other backup files (none of which worked), reinstalling the program, but none of it seems to be working. 
I'm at a loss regarding what to do. Please help.

Thanks,
A Concerned Citizen

**Comment by mondul** [comment]
What's the message in the black window?

**Comment by BigTigerM** [comment]
Hi! Thank you for responding.
I did just what you said, and the same error keeps appearing. 

**Checking NAND file...
ERROR: Could not open the file nand.bin**

In the console, it says:

[Errno 22] Invalid argument

Nothing else appears.

**Comment by mondul** [comment]
Have you tried running the helper in a different computer?

**Comment by Kodtiz3D** [comment]
Might be one (or multiple) of the following; 
The drive the `nand.bin` file is stored on is dead or dying. If this is the SD card, reformat the card to FAT32 using Disk Management or SD Formatter and use h2testw to test the SD card for errors. If there are any, re-dump the NAND with a new card.
You are running the Helper in a temporary environment, let's say running it directly from the `.zip` archive and/or by opening it when downloading (It doesn't get saved to Downloads, rather some temporary cache folder which gets cleared when not in use)
Or the drive the Helper and/or `nand.bin` file is compressed and/or encrypted by Windows. The files and folders would be colored blue if this were the case.
Seeing this isn't closed by now implies it might be solved privately, but in the off chance it is not this is my two cents.

**Comment by mondul** [comment]
No follow up from reporter, closing ticket
