### ISSUE TITLE
Korean region not supported

### ISSUE THREAD

**Issue by kimjaejundfadsf** [mondul/HiyaCFW-Helper#55]
How can I use hiyacfw?
hiyacfw run......
error : not supported region

You can also provide nand.bin.(1.4.6k)
....ㅠㅠㅋ help me..........

**Comment by mondul** [comment]
Please upload your nand dump to your google drive and share the link in order to update the helper and make it compatible with korean DSis

**Comment by kimjaejundfadsf** [comment]
[my nds nand.... korea version](https://drive.google.com/open?id=1Ju22L0dJBoWvPeyhLqS7sLGzI7o6Szpf)

very very thank you

**Comment by mondul** [comment]
Thanks. Now I'm trying to find the v512 launcher (the one from system version 1.4.0) in order to add full support.

**Comment by SAENGGAK** [comment]
I'm sorry but the latest version of Korean DSi is 1.4.6K, not 1.4.1.

**Comment by mondul** [comment]
@SAENGGAK HiyaCFW uses a modified version of the v512 launcher from the 1.4.0U/J/E/A (1.4.1K) system version, that's why the one present in the NAND dump is not used, instead it has to be downloaded from the big N servers and patched. The problem that I had is that it is not available for download, ergo the Helper at this time does not support Korea or China DSis. Someone from GBATemp provided me with a copy of the launcher and I'm in the process of testing if it can be used for Hiya.

**Comment by Chiharuuu** [comment]
I have a 1.4.1K NAND dump from my DSi if it can help, I'm eager to get HiyaCFW running on this console too.

**Comment by mondul** [comment]
@Chiharuuu That will help a lot, thanks. Someone provided me with a pre-patched launcher but does not work for running HiyaCFW from the SD card, that's why I have not released it.

**Comment by Chiharuuu** [comment]
@mondul [here](https://drive.google.com/file/d/1jTwFm6-nC-CeJi8njU5dMtSn5p9Xg0JZ/view?usp=sharing) is the NAND from my DSi, firmware 1.4.1K. If it's corrupted somehow I can always dump it again.

**Comment by kimjaejundfadsf** [comment]
1.4.6k not supported???? ㅜㅜ

**Comment by Darxmax** [comment]
Some problems with 1.4.1k
Checking NAND file...
- eMMC CID: 4DAFA512E8034D303046504100001500
- Console ID: 0820188018105102

Downloading latest HiyaCFW release...
- Extracting HiyaCFW archive...

Extracting ARM7/ARM9 BIOS from NAND...
- arm7.bin SHA1:
  67BA0E54CE49517D03AE05202B4E810AE5BCF2A6
- arm9.bin SHA1:
  A20505D56E5E280E97FA8912F8E90446991689F4

Patching ARM7/ARM9 BIOS...
- Patched arm7.bin SHA1:
  EB9C4F6E740382BADA618A20C1E18529DB641D58
- Patched arm9.bin SHA1:
  76E0A55E6A016EF638119E1129124DB4565E69E0

Prepending data to ARM9 BIOS...
- Prepended arm9.bin SHA1:
  E036465899CB4DC124AF3929BE07B4573B563249

Generating new bootloader...
- bootloader.nds SHA1:
  B654E62A044282BF60860566BEC1BE254B2336AE

Decrypting NAND...

Extracting files from NAND...
- Detected KOR console NAND dump

Downloading KOR launcher...
ERROR: Could not download KOR launcher

Cleaning...
Done

**Comment by mondul** [comment]
Still working on it, at this moment the patched launcher can't boot HiyaCFW from the SD card

**Comment by mondul** [comment]
@kimjaejundfadsf @Chiharuuu @Darxmax Made another test and it doesn't boot in no$gba, I just get a white screen. I would like some feedback on what happens on a real console. Can anyone of you download the latest release of the helper, put [this file](https://gofile.io/?c=5kDHRY) at the same folder where you extracted it, run the helper and let me know what happens on your console? Thanks!

**Comment by Darxmax** [comment]
Yep, that working.

**Comment by Chiharuuu** [comment]
Patching with the KOR launcher now works, but I can't get TwilightMenu++ to show on the system menu, or autoboot either. Tried both installing it from the Helper, and manually installing it too...

**Comment by Darxmax** [comment]
> Patching with the KOR launcher now works, but I can't get TwilightMenu++ to show on the system menu, or autoboot either. Tried both installing it from the Helper, and manually installing it too.
Yes, some problems, but i resolved by  unlaunch in option - > no button-> and choose TwilightMenu++ -> save and exit.

**Comment by Sohelvai15** [comment]
KOR launcher now works Perfectly.Thank You for Your Hard Work.

**Comment by thenist** [comment]
does anyone has this file?

**Comment by mondul** [comment]
@thenist Pushed to a new branch in 01a6902d98aa139055ef9af9a81870a34f80d5b7

**Comment by BigFarm** [comment]
It doesn't work for my dsi (1.4.6k)

Checking NAND file...
- eMMC CID: 2DCD1944173257373136354D00011500
- Console ID: 0820165406116133

Downloading latest HiyaCFW release...
- Extracting HiyaCFW archive...

Extracting ARM7/ARM9 BIOS from NAND...
- arm7.bin SHA1:
  67BA0E54CE49517D03AE05202B4E810AE5BCF2A6
- arm9.bin SHA1:
  A20505D56E5E280E97FA8912F8E90446991689F4

Patching ARM7/ARM9 BIOS...
- Patched arm7.bin SHA1:
  EB9C4F6E740382BADA618A20C1E18529DB641D58
- Patched arm9.bin SHA1:
  76E0A55E6A016EF638119E1129124DB4565E69E0

Prepending data to ARM9 BIOS...
- Prepended arm9.bin SHA1:
  E036465899CB4DC124AF3929BE07B4573B563249

Generating new bootloader...
- bootloader.nds SHA1:
  B654E62A044282BF60860566BEC1BE254B2336AE

Decrypting NAND...

Extracting files from NAND...
- Detected KOR console NAND dump

Downloading KOR launcher...
ERROR: Could not download KOR launcher

Cleaning...
Done

**Comment by kimjaejundfadsf** [comment]
Opening HiyaCFW Helper...
Initializing GUI...
Searching for 7-Zip in the Windows registry...
Searching for 7-Zip in the 32-bit Windows registry...
7-Zip not found. Will use fatcat for extraction.
TWLTool v1.6.1
  by WulfyStylez
  Special thanks to CaitSith2

reading consoleid/CID from nocashinfo block
Processing twln...
0.00 % complete.
12.14 % complete.
24.28 % complete.
36.42 % complete.
48.56 % complete.
60.70 % complete.
72.84 % complete.
84.98 % complete.
97.11 % complete.
100.00% complete.
Processing twlp...
0.00 % complete.
76.42 % complete.
100.00% complete.
Crypt complete!

[WinError 5] 액세스가 거부되었습니다
Exception in thread Thread-4:
Traceback (most recent call last):
  File "HiyaCFW_Helper.py", line 592, in extract_nand
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
PermissionError: [WinError 5] 액세스가 거부되었습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "HiyaCFW_Helper.py", line 605, in extract_nand
NameError: name 'exe' is not defined


........ㅠㅠ

**Comment by kimjaejundfadsf** [comment]
https://drive.google.com/open?id=1BVcDPG1iwWeC2Hen6qoe4rVy6FRddq_H

**Comment by kimjaejundfadsf** [comment]
kor luncher Works 
very very gooooooooooooooooooooooooooooooooood
1. Uploaded kor file to Naver
2. Python source modification
  with rlopen('myfile url/' +
                    self.launcher_region) as src, open(self.launcher_region, 'wb') as dst:
3. pyinstall HiyaCFW_Helper.py
4. Put the window folder in the existing version of Windows
5. cfw proceeded.


=========Progress was successful===========

I was busy and now I have to check.
I'm very sorry.
Thank you so much for your hard work.

**Comment by kimjaejundfadsf** [comment]
console log

Opening HiyaCFW Helper...
Initializing GUI...
Searching for 7-Zip in the Windows registry...
Searching for 7-Zip in the 32-bit Windows registry...
7-Zip not found. Will use fatcat for extraction.
TWLTool v1.6.1
  by WulfyStylez
  Special thanks to CaitSith2

CTR:
000000: 00 66 02 00 00 9a fd ff ff 99 fd ff 00 00 00 00  .f..............
Normalkey:
000000: 98 ee 80 80 00 6c b4 f6 3a c2 6e 62 f9 ec 34 ad  .....l..:.nb..4.
CTR:
000000: 00 76 02 00 00 8a fd ff ff 89 fd ff 00 00 00 00  .v..............
Normalkey:
000000: 98 ee 80 80 00 6c b4 f6 3a c2 6e 62 f9 ec 34 ad  .....l..:.nb..4.
Nintendo DS rom tool 1.24 - Nov  2 2005 00:24:53 by Rafael Vuijk (aka DarkFader)
TWLTool v1.6.1
  by WulfyStylez
  Special thanks to CaitSith2

reading consoleid/CID from nocashinfo block
Processing twln...
0.00 % complete.
12.14 % complete.
24.28 % complete.
36.42 % complete.
48.56 % complete.
60.70 % complete.
72.84 % complete.
84.98 % complete.
97.11 % complete.
100.00% complete.
Processing twlp...
0.00 % complete.
76.42 % complete.
100.00% complete.
Crypt complete!

Extracting /sys/log/product.log to C:/test/output/sys/log/product.log
Extracting /sys/log/sysmenu.log to C:/test/output/sys/log/sysmenu.log
Extracting /sys/log/shop.log to C:/test/output/sys/log/shop.log
Extracting /sys/HWINFO_S.dat to C:/test/output/sys/HWINFO_S.dat
Extracting /sys/HWINFO_N.dat to C:/test/output/sys/HWINFO_N.dat
Extracting /sys/cert.sys to C:/test/output/sys/cert.sys
Extracting /sys/HWID.sgn to C:/test/output/sys/HWID.sgn
Extracting /sys/TWLFontTable.dat to C:/test/output/sys/TWLFontTable.dat
Extracting /sys/dev.kp to C:/test/output/sys/dev.kp
Extracting /title/00030017/484e414b/data/private.sav to C:/test/output/title/00030017/484e414b/data/private.sav
Extracting /title/00030017/484e414b/content/title.tmd to C:/test/output/title/00030017/484e414b/content/title.tmd
Extracting /title/00030017/484e414b/content/00000005.app to C:/test/output/title/00030017/484e414b/content/00000005.app
Extracting /title/00030015/484e4f4b/data/ec.cfg to C:/test/output/title/00030015/484e4f4b/data/ec.cfg
Extracting /title/00030015/484e4f4b/content/00000000.app to C:/test/output/title/00030015/484e4f4b/content/00000000.app
Extracting /title/00030015/484e4f4b/content/title.tmd to C:/test/output/title/00030015/484e4f4b/content/title.tmd
Extracting /title/00030015/484e424b/content/title.tmd to C:/test/output/title/00030015/484e424b/content/title.tmd
Extracting /title/00030015/484e424b/content/00000001.app to C:/test/output/title/00030015/484e424b/content/00000001.app
Extracting /title/00030015/484e464b/data/private.sav to C:/test/output/title/00030015/484e464b/data/private.sav
Extracting /title/00030015/484e464b/data/ec.cfg to C:/test/output/title/00030015/484e464b/data/ec.cfg
Extracting /title/00030015/484e464b/content/title.tmd to C:/test/output/title/00030015/484e464b/content/title.tmd
Extracting /title/00030015/484e464b/content/00000006.app to C:/test/output/title/00030015/484e464b/content/00000006.app
Extracting /title/0003000f/484e4341/content/00000002.app to C:/test/output/title/0003000f/484e4341/content/00000002.app
Extracting /title/0003000f/484e4341/content/title.tmd to C:/test/output/title/0003000f/484e4341/content/title.tmd
Extracting /title/0003000f/484e4841/content/title.tmd to C:/test/output/title/0003000f/484e4841/content/title.tmd
Extracting /title/0003000f/484e4841/content/00000006.app to C:/test/output/title/0003000f/484e4841/content/00000006.app
Extracting /title/0003000f/484e4c4b/content/title.tmd to C:/test/output/title/0003000f/484e4c4b/content/title.tmd
Extracting /title/0003000f/484e4c4b/content/00000006.app to C:/test/output/title/0003000f/484e4c4b/content/00000006.app
Extracting /title/00030005/484e444b/content/00000000.app to C:/test/output/title/00030005/484e444b/content/00000000.app
Extracting /title/00030005/484e444b/content/title.tmd to C:/test/output/title/00030005/484e444b/content/title.tmd
Extracting /title/00030005/484e454b/content/00000000.app to C:/test/output/title/00030005/484e454b/content/00000000.app
Extracting /title/00030005/484e454b/content/title.tmd to C:/test/output/title/00030005/484e454b/content/title.tmd
Extracting /title/00030005/484e494b/data/private.sav to C:/test/output/title/00030005/484e494b/data/private.sav
Extracting /title/00030005/484e494b/content/00000000.app to C:/test/output/title/00030005/484e494b/content/00000000.app
Extracting /title/00030005/484e494b/content/title.tmd to C:/test/output/title/00030005/484e494b/content/title.tmd
Extracting /title/00030005/484e4b4b/data/private.sav to C:/test/output/title/00030005/484e4b4b/data/private.sav
Extracting /title/00030005/484e4b4b/content/00000000.app to C:/test/output/title/00030005/484e4b4b/content/00000000.app
Extracting /title/00030005/484e4b4b/content/title.tmd to C:/test/output/title/00030005/484e4b4b/content/title.tmd
Extracting /ticket/00030017/484e414b.tik to C:/test/output/ticket/00030017/484e414b.tik
Extracting /ticket/00030015/484e4f4b.tik to C:/test/output/ticket/00030015/484e4f4b.tik
Extracting /ticket/00030015/484e424b.tik to C:/test/output/ticket/00030015/484e424b.tik
Extracting /ticket/00030015/484e464b.tik to C:/test/output/ticket/00030015/484e464b.tik
Extracting /ticket/0003000f/484e4341.tik to C:/test/output/ticket/0003000f/484e4341.tik
Extracting /ticket/0003000f/484e4841.tik to C:/test/output/ticket/0003000f/484e4841.tik
Extracting /ticket/0003000f/484e4c4b.tik to C:/test/output/ticket/0003000f/484e4c4b.tik
Extracting /ticket/00030005/484e444b.tik to C:/test/output/ticket/00030005/484e444b.tik
Extracting /ticket/00030005/484e454b.tik to C:/test/output/ticket/00030005/484e454b.tik
Extracting /ticket/00030005/484e494b.tik to C:/test/output/ticket/00030005/484e494b.tik
Extracting /ticket/00030005/484e4b4b.tik to C:/test/output/ticket/00030005/484e4b4b.tik
Extracting /shared1/TWLCFG0.dat to C:/test/output/shared1/TWLCFG0.dat
Extracting /shared1/TWLCFG1.dat to C:/test/output/shared1/TWLCFG1.dat
Extracting /shared2/launcher/wrap.bin to C:/test/output/shared2/launcher/wrap.bin
Extracting /shared2/0000 to C:/test/output/shared2/0000


gui log

Checking NAND file...
- eMMC CID: BC22441897034D303046504100001500
- Console ID: 0820162105089131

Downloading latest HiyaCFW release...
- Extracting HiyaCFW archive...

Extracting ARM7/ARM9 BIOS from NAND...
- arm7.bin SHA1:
  67BA0E54CE49517D03AE05202B4E810AE5BCF2A6
- arm9.bin SHA1:
  A20505D56E5E280E97FA8912F8E90446991689F4

Patching ARM7/ARM9 BIOS...
- Patched arm7.bin SHA1:
  EB9C4F6E740382BADA618A20C1E18529DB641D58
- Patched arm9.bin SHA1:
  76E0A55E6A016EF638119E1129124DB4565E69E0

Prepending data to ARM9 BIOS...
- Prepended arm9.bin SHA1:
  E036465899CB4DC124AF3929BE07B4573B563249

Generating new bootloader...
- bootloader.nds SHA1:
  B654E62A044282BF60860566BEC1BE254B2336AE

Decrypting NAND...

Extracting files from NAND...
- Detected KOR console NAND dump

Downloading KOR launcher...
- Decrypting launcher...
- Patched launcher SHA1:
  1CCA531D4943E7B0ED6924AC2CD8D4F90E627C69

Copying HiyaCFW files...

Downloading latest TWiLight Menu++ release...
- Extracting TWiLightMenu archive...

Copying TWiLightMenu files...

Cleaning...
Done!
Eject your SD card and insert it into your DSi
