### ISSUE TITLE
Any possible to support Chinese region?

### ISSUE THREAD

**Issue by megakusa** [mondul/HiyaCFW-Helper#56]
Since I found that this tool is not supported with Chinese region, I tried to install hiyaCFW manually. But I failed (I tried the JAP-KOR IPS patch). If you are interested to add support to Chinese region, I have a nand with system version 1.4c which I think the launcher is also v512.

[nand.bin](https://drive.google.com/open?id=1jIDt2HGRGUOoVyU8cli1YWakCyyfCvik)

**Comment by mondul** [comment]
Thanks! I'll check if it needs a different patching procedure.

**Comment by mondul** [comment]
Fixed in 19df4a4
