### ISSUE TITLE
Issue with Twilight Menu++ 8.5.0?

### ISSUE THREAD

**Issue by rogersa2k** [mondul/HiyaCFW-Helper#57]
I am using HiyaCFW-Helper 3.4 on Windows 10 and it was completely fine until today. Now I see the following. Because Twilight Menu++ just got updated to 8.5.0 I suspect it has something to do with that:

Exception in thread Thread-12:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "HiyaCFW_Helper.py", line 718, in install_twilight
  File "distutils\dir_util.py", line 124, in copy_tree
distutils.errors.DistutilsFileError: cannot copy tree 'DSi - CFW users\SDNAND root': not a directory

**Comment by MR4Y** [comment]
I'm experiencing the exact same error as well. The error doesn't happen when you choose to install HyiaCFW instead (unticking the TwilightMenu++), so it's probably related to Twilight Menu++

**Comment by rogersa2k** [comment]
Yeah, something is wrong with the TWiLightMenu.7z file it is downloading. I manually downloaded the correct file for 8.5.0, commented out the following section, and the script works just fine:

            with urlopen(latest['assets'][0]
                ['browser_download_url']) as src, open(filename, 'wb') as dst:
                copyfileobj(src, dst)

**Comment by mondul** [comment]
Fixed in 116f430301e1177d0804f50801c392206a954afb
