### ISSUE TITLE
Hiya CFW Helper - ERROR: CANNOT GET HIYA CFW

### ISSUE THREAD

**Issue by malek78i** [mondul/HiyaCFW-Helper#6]
Hey guys!

As you can read in the title, I have a problem with the helper. I get ERROR: CANNOT GET HIYA CFW. I tried downloading the hiyacfw package but the error still persists. What can I do? Thank you!

**Comment by mondul** [comment]
Please check if your computer has the correct date and time set up. If not, please attach the output of the command window (the black one).

**Comment by mondul** [comment]
In the next release you will be able to use your own HiyaCFW.7z and/or TWiLightMenu.7z

**Comment by malek78i** [comment]
Okay. Thank you!

**Comment by nmcc1212** [comment]
^has that come yet, if so how?

**Comment by malek78i** [comment]
Yes. I put the HiyaCFW and the Twilightmenu++ pack(s) to the HiyaCFW Helper folder and started it

**Comment by nmcc1212** [comment]
ok thanks!

I still have the error of something to do with Darwin 7za?

any help?

**Comment by malek78i** [comment]
Sorry. Whats Darwin 7za😁?

**Comment by malek78i** [comment]
If you mean for Mac, then I can't help you on it. I only and use Windows. I'm sorry!

**Comment by nmcc1212** [comment]
ok, where is the exe file for this?

**Comment by malek78i** [comment]
Of the HiyaCFW Helper?

**Comment by nmcc1212** [comment]
yes

**Comment by malek78i** [comment]
Here is a link:
https://github.com/mondul/HiyaCFW-Helper/releases/tag/v3.0.1

It exists 3 versions of the helper:
Python3
Windows 32 bit
Windows 64 bit

**Comment by nmcc1212** [comment]
thanks :)

**Comment by malek78i** [comment]
You are welcome😁!
