### ISSUE TITLE
ERROR: failed to read Launcher's title.tmd

### ISSUE THREAD

**Issue by SpardaGabriel** [mondul/HiyaCFW-Helper#60]
Someone help me, I'm always trying and get the same error...

**Comment by mondul** [comment]
Which region is your DSi?

**Comment by SpardaGabriel** [comment]
> Which region is your DSi?

US

**Comment by mondul** [comment]
Please test your NAND in no$gba, does it boot?

**Comment by SpardaGabriel** [comment]
> Please test your NAND in no$gba, does it boot?

Error 2-2435-8325

**Comment by mondul** [comment]
You will need to re-dump your NAND, preferably in another micro SD. Scan it for errors prior inserting it in your DSi

**Comment by SpardaGabriel** [comment]
It was the NAND and the SD that had problems...
