### ISSUE TITLE
I have a mac and am getting the same error as many people. But cant find help.

### ISSUE THREAD

**Issue by theluxioriousluxray** [mondul/HiyaCFW-Helper#61]
Checking NAND file...
- eMMC CID: AB567FCA71034D303046504100001500
- Console ID: 08A1842112105136

Downloading latest HiyaCFW release...
ERROR: Could not get HiyaCFW

This is the error i've been getting.

**Comment by mondul** [comment]
Install python thru homebrew, please check the readme

**Comment by theluxioriousluxray** [comment]
Where is the read me? Also why did you close the issue... my issue hasn’t been resolved

**Comment by mondul** [comment]
It's at the homepage of the repo. Here's what it says about your issue:
Python 3.5 or greater, you can install it with one of these options:
[Recommended] Homebrew (install homebrew by running /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" in a terminal window, then brew install python).
[Might have issues] The latest installer from the python.org releases page (3.7.3 at the time of this writing). NOTE: Using this option you might need to go to Applications > Python 3.<version> and run Install Certificates.command. This will avoid the "Could not get HiyaCFW" error.

**Comment by theluxioriousluxray** [comment]
I tried that last thing but still got the error. I wish there was a video tutorial for Mac users...

**Comment by mondul** [comment]
Uninstall your python 3 and try the Homebrew route, just copy and paste the commands

**Comment by theluxioriousluxray** [comment]
how do i uninstall it? sorry for all the questions

**Comment by mondul** [comment]
This might help you:
https://osxuninstaller.com/uninstall-guides/properly-uninstall-python-mac/

**Comment by theluxioriousluxray** [comment]
Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff87fc9210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1077bbdc8). One of the two will be used. Which one is undefined.

I just followed everything. This is what it said in Terminal after I got the "Checking NAND file...
- eMMC CID: AB567FCA71034D303046504100001500
- Console ID: 08A1842112105136

Downloading latest HiyaCFW release...
ERROR: Could not get HiyaCFW" error code... Do you know what it means.. (unstalling python didnt work.)

**Comment by mondul** [comment]
What message are you getting in the terminal?

**Comment by theluxioriousluxray** [comment]
Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff87fc9210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1077bbdc8). One of the two will be used. Which one is undefined.

**Comment by mondul** [comment]
Doesn't show anything after that?

**Comment by theluxioriousluxray** [comment]
nope

**Comment by theluxioriousluxray** [comment]
I just noticed that right when i choose my NAND file from the drop-down, the message "Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff87fc9210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1077bbdc8). One of the two will be used. Which one is undefined." shows up.

**Comment by theluxioriousluxray** [comment]
Maybe we should try using the second option to download python?
