### ISSUE TITLE
ERROR: Extractor failed

### ISSUE THREAD

**Issue by KunaiiAF** [mondul/HiyaCFW-Helper#63]
LOG:
Checking NAND file...
- eMMC CID: 6DEA248EC9034D303046504100001500
- Console ID: 0820211801116127

Preparing HiyaCFW...
- Extracting HiyaCFW archive...
ERROR: Extractor failed

When I'm trying to do it we in a Video then come this Error.. pls help :(
Version 3.4.1

**Comment by mondul** [comment]
Which OS?

**Comment by AnalogHero** [comment]
Have the same problem on windows 7.

**Comment by mondul** [comment]
What message are you both getting in the command window?

**Comment by AnalogHero** [comment]
The message was the same as the OP has written.

**Comment by mondul** [comment]
I mean, in the black console window

**Comment by AnalogHero** [comment]
Cant tell... Dont have access to windows machine atm. From top of my head it was:

Checking registry for 7zip...

Extracting hiyacfw archive...
Extracting failed

**Comment by mondul** [comment]
Try reinstalling 7zip to the latest version according to your platform (x86 or x64)

**Comment by mondul** [comment]
Removed 7-Zip dependency in 7b1a92155e52f3e48a5c9f271fe7062d9cbe5f91
Closing ticket.
