### ISSUE TITLE
0.fat error.

### ISSUE THREAD

**Issue by FallingBoi** [mondul/HiyaCFW-Helper#64]
Well, after a time of wanting hack my DSi a day i did it but my mismatch failed in Unlauncher 1.9 (Fixed Already) so i was going with a Helper and in the process of that i was going to install HiyaCFW and when its get done i got a strange error who say "0.fat"
"Can not open the file as [FAT] archive" I dont know if was by my SD card cause its higher than 2 GB (4) Or the 7-Zip, i got the final version 64-bit (19.00) But it dont works but after a while i used the HiyaCFW 2.9.9.5 (OSFMount 2.0) and it worked better than the 3.1.4, anyways great work with those DSi Hacks i hope it can be fixed so people like me can hack they DSi ! Greetings from Mexico!

-MxQueso (This is my alt)

**Comment by Kodtiz3D** [comment]
I helped them fix the Mismatch in FAT copies error in the Unlaunch installation by copying hex with the values listed here http://forums.nesdev.com/viewtopic.php?f=23&t=17581&start=90#p226740
>Instead of scandisk, you could also load the decrypted image into a hex editor, and manually copy the 1st FAT to 2nd FAT (1st FAT should be at offset 0010F000h, the FAT size is 6800h bytes, followed by 2nd FAT at offset 00115800h with same size), that should work too, as long as you don't screw it up. -nocash

I'm unsure if this is an issue with the NAND backup or how 7-Zip treated this backup. Trying to open the backup in 7-Zip's file manager didn't work but mounting it in OSFMount 2.0 worked.
Using an older HiyaCFW Helper using OSFMount 2.0 worked just fine, version 2.9.9.5 was used instead to get HiyaCFW up and running.

**Comment by mondul** [comment]
Removed 7-Zip dependency in 7b1a92155e52f3e48a5c9f271fe7062d9cbe5f91
Closing ticket.
