### ISSUE TITLE
Unlaunch option

### ISSUE THREAD

**Issue by mbhz** [mondul/HiyaCFW-Helper#7]
Hello!)
Will be the possibility to choose the Unlaunch's version to install in future releases? Or somehow replace the downloadable version to the desired?
It's will be very helpfull ...

**Comment by mondul** [comment]
I chose the v1.4 because it's the last one to work with the manual TMD injection method. For more recent unlaunch versions it should be installed using No$GBA (only works if you have the right BIOS files, google for "DSiEmulationSetup" if you don't have them).
