### ISSUE TITLE
7za quit unexpectedly.

### ISSUE THREAD

**Issue by maiz00** [mondul/HiyaCFW-Helper#73]
Hi, 
I have been trying the whole 2 days to resolve this issue.

Working on Mac (10.10.5), 
I have install homebrew python3 too.
When I run ./HiyaCFW_Helper.py  it got to the download HiyaCFW.7z, but came out with the '7za quit unexpectedly'

I run using python3 command in terminal
python3 /User/path/to/HiyaCFW_Helper.py 
It load and came this :-

"TWLTool not found. Please make sure the Darwin folder is at the same location as this script, or run it again from the terminal:

$ ./HiyaCFW_Helper.py"

I ran out of idea now.

**Comment by maiz00** [comment]
Report that came with the error.
It kinda same issue when I just try to click the binaries files inside the Darwin folder.

[Apple-report.txt](https://github.com/mondul/HiyaCFW-Helper/files/3721662/Apple-report.txt)

**Comment by maiz00** [comment]
My bad! 
I stumble upon this web https://opensource.com/article/19/5/python-3-default-mac
and check that there is no homebrew python installed! Maybe some happen when I try to install it last time. 

Will engage in homebrew install. First to uninstall any left over Python 3 install last time thru dmg

**Comment by maiz00** [comment]
I have install python using the installer for Mac, since it take to much resources dan conflict intalling it using homebrew.

After call the directory and manage to run the GUI, still got this problem

>>> exec(open("HiyaCFW_Helper.py").read())
Opening HiyaCFW Helper...
Initializing GUI...
[Errno 8] Exec format error: 'Darwin/7za'

I have made the chmod 777 for the 7za file, still nothing.

**Comment by mondul** [comment]
You need to update to at least High Sierra, or assist me compiling 7za on your machine.

**Comment by maiz00** [comment]
Thank you for the clarification. It the OS ...i see.

I be delight to assist you. 
Just to be clear, I'm not a programmer.
Do enlighten me sir.

**Comment by mondul** [comment]
Hi, it's simple. You will need to install the XCode command line tools by running:
    xcode-select --install
Then you can get the 7za's source code, linked in the Readme and decompress it to an accessible folder, like the Desktop. After that open a terminal, browse to the extracted folder using the `cd` command, like:
    cd ~/Desktop/7za
And run:
    ./configure
    make
That will generate the `7za` binary for your OS version.

**Comment by mondul** [comment]
No follow up from reporter, closing ticket
