### ISSUE TITLE
KOR launcher

### ISSUE THREAD

**Issue by RocketRobz** [mondul/HiyaCFW-Helper#75]
The JAP .ips patch also works with the Korean launcher, so any chance the KOR launcher can be added?

EDIT: Here's a NAND dump, provided by @FlameKat53
https://mega.nz/#!qNx3XCpQ!BXsTIvvv6CCrR4jGAeYZtmO_bhjEHtqt5Hn1Eg9ztYw

**Comment by FlameKat53** [comment]
(And that NAND was given to me by @Epicpkmn11, they say it's 1.4.2K)

**Comment by mondul** [comment]
In #55 someone provided me with a 1.4.1K dump, which I used to get the launcher, patched it but when tested all I get is a blank screen, but when I installed Hiya directly in the NAND works fine. Checked with Apache Thunder and it seems the redirection part of the patch is not working, and we were not able to fix it. Do you think by using the launcher from this dump will work?

**Comment by Kodtiz3D** [comment]
I think the main issue with Korean support is the lack of a Launcher in 1.4
DSiBrew says Korean regions only got v768 (1.4.1). As hiyaCFW is using some form of RocketLauncher based method hence requiring Launcher version 1.4. So hiyaCFW probably will not work without a new Launcher bug being found on newer versions.

**Comment by Kodtiz3D** [comment]
Here is a link to that if you were not aware https://dsibrew.org/wiki/Title_list#Korea_2

**Comment by RocketRobz** [comment]
A brand new .ips patch for KOR launcher (by @R-YaTian) has been added to hiyaCFW v1.3.3.
Can someone try again with the new patch?

**Comment by R-YaTian** [comment]
Currently can use the branches https://github.com/mondul/HiyaCFW-Helper/tree/KOR
And use this https://github.com/R-YaTian/HHF-Toolkit/raw/HiyaCFW-Helper-R3/launchers/KOR

**Comment by Epicpkmn11** [comment]
(addded in #111)
