### ISSUE TITLE
1.4.6C Unlaunch 2.0 Brick

### ISSUE THREAD

**Issue by david-zzj** [mondul/HiyaCFW-Helper#76]
After i installed unlaunch correctly, console reboot to black screen... 
I have fwtool nand backup.

**Comment by Kodtiz3D** [comment]
Issue is unrelated to the Helper, but hold `A` on boot and see if Unlaunch's filemenu appears. If not try booting without the SD card inserted, and also try holding `A` to attempt to boot into the filemenu.

**Comment by david-zzj** [comment]
hold A, power, black screen..
eject SD,  power, black screen.. 
I found both screens does not have backlight.. totally black...

**Comment by david-zzj** [comment]
I know this is not helper issues, sorry. 
but I have no idea to solve this error, please give me some advice.

**Comment by Kodtiz3D** [comment]
If `A` doesn't work try `A` + `B` on boot without the SD card inserted. `A` is normally supposed to be bound for the filemenu but can be changed. `A` + `B` is hardcoded to be the filemenu, so I would try that next.
What guide are you using, and what have you done up to this point in the modding process?

**Comment by david-zzj** [comment]
Try A+B on boot, it got the same BSOD... 
I follow the dsi.cfw guide, all process seem ok as usual. 
Install Unlaunch v2.0 top screen display Success too.

**Comment by Kodtiz3D** [comment]
Has the DSi sustained any falls or other hard knocks during or after installing Unlaunch?
I would open it up and see if any of the ribbon cables are disconnected or pinched.

**Comment by Kodtiz3D** [comment]
The DSi doesn't have any sort of fatal literal blue screen, unless you are saying the backlight still doesn't turn on. This issue will likely require a hardmod (hardware modification) to function if it's not a ribbon cable issue. Tell this to nocash on nesdev or via email as there isn't exactly much we can do after this.

**Comment by david-zzj** [comment]
OK, i try to contact nocash.

**Comment by mondul** [comment]
Not a helper's issue, closing ticket.

**Comment by lukesvw** [comment]
Did you ever manage to fix your problem?

**Comment by david-zzj** [comment]
Not yet. The only way is hardmod to restored nand bak.
