### ISSUE TITLE
Could not download JAP launcher

### ISSUE THREAD

**Issue by david-zzj** [mondul/HiyaCFW-Helper#78]
Please tell me which url does Helper download launcher for each region.
I get the url error for many days. My network is ok, no proxy.
Last two weeks helper works fine, but from last week it goes wrong.

![JAP launcher](https://user-images.githubusercontent.com/22125266/68016925-879b2680-fcd0-11e9-99fb-e623debe49d9.jpg)

**Comment by mondul** [comment]
https://github.com/mondul/HiyaCFW-Helper/tree/master/launchers

**Comment by david-zzj** [comment]
That‘s a strange things for me.
I can download anyother files from https://github.com/mondul/HiyaCFW-Helper/,
except https://github.com/mondul/HiyaCFW-Helper/tree/master/launchers.

**Comment by mondul** [comment]
Try disabling Windows Firewall while you run the helper, or use a VPN.

**Comment by mondul** [comment]
Not a helper's issue, closing ticket.
