### ISSUE TITLE
HiyaCFW-Helper does not handle canceling/closing the "sd card directory" picker

### ISSUE THREAD

**Issue by Raqbit** [mondul/HiyaCFW-Helper#8]
When you click "cancel" when picking a directory to create the SDNAND, HiyaCFW-Helper does not recognize the cancel and uses the value returned by TK as path.

After reading up on it this seems to be `""`, although I haven't looked enough through the code to see where it would put the files (I accidentally just did this, so it would be nice if you could tell me :P)

This bug is a bit scary, especially since it's running as root and could overwrite any file when you think it's canceling.

**Comment by mondul** [comment]
It should put the files/folders at the helper's location.
