### ISSUE TITLE
No Binaries for Alternate Platforms

### ISSUE THREAD

**Issue by Kodtiz3D** [mondul/HiyaCFW-Helper#81]
The latest release (3.5.1) does not include MacOSX or Linux versions. Users would need to go back a few versions to use the Helper on their OS. `Darwin`/`Linux` folders with the Helper's dependencies are not included. 
Wine could work, yes, but you'd need to state to try Wine in the README. But including specific MacOSX and Linux binaries alongside Windows would be more user friendly. Version 3.5 has Windows and MacOSX/Linux versions, I am unsure on what changes would need to be made to either the Helper script or the release page for 3.5.1 for this to work.

**Comment by mrpapersonic** [comment]
The latest release didn't even work for me. Use 3.5.

**Comment by Kodtiz3D** [comment]
Care to go in a bit more detail? Perhaps in a new issue rather than commenting on this one.
What OS are you using? Which guide were you using? Have you followed said guide fully and accurately? If an error shows up in one of the hiyaCFW Helper windows, what is the error?

**Comment by mondul** [comment]
Published new release for all platforms, closing ticket.
