### ISSUE TITLE
ERROR: Could not get HiyaCFW

### ISSUE THREAD

**Issue by serayutrain** [mondul/HiyaCFW-Helper#82]
I am using windows 8.1 and  using HiyaCFW-helper v3.6-Win

Checking NAND file...
-eMMC CID: 9C0057DF78034D303046504100001500
-Console ID: 0820131415111140

Downloading latest HiyaCFW release.....
ERROR: Could not get HiyaCFW

Please help i want play gba game on dsi.😭😭😭

**Comment by mondul** [comment]
Which error are you getting in the command line output (the black text-only window)? Did you allow the helper to access the internet through the windows firewall?

**Comment by serayutrain** [comment]
@mondul i turned windows firewall off and not turn on internet.but still error

**Comment by serayutrain** [comment]
Still error: could not get hiyacfw. I want post image but i dont undersatand how LOL

**Comment by serayutrain** [comment]
Stil error: could not get hiyacfw😭😭. I want post image but i don't understand how LOL😅

**Comment by Kodtiz3D** [comment]
The HiyaCFW Helper requires internet access, or a device that can get the needed files from online. The latter solution is not ideal however, so please enable internet on your PC and retry the process.
