### ISSUE TITLE
ERROR: Could not get HiyaCFW

### ISSUE THREAD

**Issue by icannotcfwmydsipleasehelp** [mondul/HiyaCFW-Helper#83]
Checking NAND file...

Downloading latest HiyaCFW release...
ERROR: Could not get HiyaCFW

error pops up when i try to install hiya, running on a mac with python 3.8.
tried running Install Certificates.command but i just get invalid syntax

**Comment by mondul** [comment]
Did you install python through homebrew?

**Comment by evnb** [comment]
I'm getting this same issue. I have python3 installed through homebrew and have tried sudo

**Comment by mondul** [comment]
If you had python in the applications folder, your system was using that one instead of the one that homebrew installed. Great you were able so solve that. Closing ticket.
