### ISSUE TITLE
EUR Region not supported.

### ISSUE THREAD

**Issue by am714** [mondul/HiyaCFW-Helper#85]
I first tried with 1.4E(I was on that version because to install 4swordhax) and got unknown console region, updated to 1.4.5E and got unsupported console region. Did I do anything wrong?

Here is the 1.4.5E nand.bin(In a .rar file): https://drive.google.com/open?id=1Ov_QoPQNEQ9YYr4-8jK2JOO9oyV53Ru8

**Comment by mondul** [comment]
Your launcher folder was uppercased, don't know if that's due 4swordhax, but that's not normal. Fixed in a4423b70ca21ac985a905dc501c4917c464622a6
