### ISSUE TITLE
[WINDOWS] Error: Could not get HiyaCFW

### ISSUE THREAD

**Issue by petregeus** [mondul/HiyaCFW-Helper#87]
Windows 7 x64, 7-zip 19.00 x86, HiyaCFW Helper 3.6.1 (Win)

-Error occurs whether nand.bin is on SD or moved to OS/app drive.
-Error occurs whether running as admin or not.

Wifi connection tests out fine, stock firewall settings, fairly fresh install of Win7 Home with all updates. (All apps were downloaded only minutes prior.)
Time is set correctly and synced with time.windows.com.

Screenshot of error and terminal details:
![error](https://user-images.githubusercontent.com/52760226/71386194-686e9600-25a9-11ea-9771-3047b3fa2bd0.png)

**Comment by mondul** [comment]
Follow this steps:
https://community.spiceworks.com/topic/584022-missing-or-invalid-root-certificates-on-windows-7-64bit

If that does not work for you, use the python version including the Windows folder from the Windows release archive

**Comment by petregeus** [comment]
Thanks for the reply. So it turns out that updating the root certificates works, but the method in the article you linked is no longer valid. (Microsoft no longer offers a public link for updroot.exe, and ideally the updated certificates need to be pulled via certutil on a Win10 machine.) Kaspersky has an updated method and a link to the update utility hosted on their servers here: https://support.kaspersky.com/13727

This worked for me, and I was able to run HiyaCFW on that Win7 Home install without the need to install Python. However, I suggest adding a note or reference to the Kaspersky KB article.

...OTOH, maybe this will no longer be relevant after general Win7 support ends next month?

Thanks again.

**Comment by mondul** [comment]
Hi, great you were able to solve your issue. Hadn't added that to the readme as W7 is ten years old and mostly everybody is using W10 these days. Closing ticket.
