### ISSUE TITLE
ERROR: Can not open the file as [7z] archive

### ISSUE THREAD

**Issue by Jalkhov** [mondul/HiyaCFW-Helper#91]
I'm having this problem on Windows 7 32 Bits.

![aaaaa](https://user-images.githubusercontent.com/36505934/74289696-1ecb3d80-4d06-11ea-8f43-fca057abe932.PNG)

I saw that the dependency was removed with 7Zip so I don't know if it has anything to do with having 7Zip installed.

**Comment by Epicpkmn11** [comment]
I'm going to close this as its an old support issue, if you still need help then please join the [DS⁽ⁱ⁾ Mode hacking Discord server](https://discord.gg/yD3spjv)
