### ISSUE TITLE
Won't boot with more than 2GB despite TWMenu

### ISSUE THREAD

**Issue by beyondFOX42** [mondul/HiyaCFW-Helper#92]
I got it to work with a 32GB San Disk and CFWhelper 1.51 and TWmenu 9.5.2 a few month ago (after it failed to extract a few TWm a few times)

but now I tried with the latest version (of both) for my friend with a 16GB Sandisk and it won't boot 

(I know I can always boot directly into TWm but he wants to have it like I do)

I also tried 1.51 again and forced it to use an older version 9.52, 9.51 or 9.50
 (not sure which because I downloaded them on 26th and there were 2 updates on that day, I hope that 9.52 will make it work but I don't know how to compile the Source Code)

but that didn't work either.

Is there a way I can manually make it work if I have a SD that boots my DSi and a SD that works correctly for his DSi apart from the 2GB issue? 

That both are DSi XL shouldn't change anything right? 

I tried around 15 times btw (but no method more than twice I think)

**Comment by beyondFOX42** [comment]
Or actually I tried the older versions more than twice and that's how I got 15

**Comment by beyondFOX42** [comment]
Also forgot to mention: there's no error message and the helper claims that Twilight Menu is properly copied and everything I also get the Eject Message

**Comment by Epicpkmn11** [comment]
Sorry for the very late response, but I'm cleaning up the old issues on here, if you still need help, is this the "An error has occurred..." problem? If so then try running https://github.com/Epicpkmn11/dfc/releases
