### ISSUE TITLE
Explain the 32-bit signed overflow error

### ISSUE THREAD

**Issue by NightYoshi370** [mondul/HiyaCFW-Helper#93]
Please explain the signed overflow error that occurs in hiyaCFW. To explain what I mean, the reason why SD cards with 3-4/7-8 GB of free space won't let normal menu boot is because of the way the system menu was made. It uses a 32-bit signed-int, which means it can go into the negative numbers. The way to fix this is to have 1-2/5-6/9-10 and so on free space.

Additionally, you should offer to make this dummy file

**Comment by mondul** [comment]
This tool is only for installing HiyaCFW, I'm not familiar on how the custom firmware works. Not a helper's issue, closing ticket.

**Comment by NightYoshi370** [comment]
This *can* be part of the helper. I'm asking if it could possibly detect the free space on the SD card and see whether or not its worthy of getting dummy files.

**Comment by mondul** [comment]
I see you are an advanced user. People normally use the helper for installing HiyaCFW together with TWiLightMenu++, so I did not worry if a >4GiB card was being used. I did try to check if the path used for extraction was a drive but didn't work in my OS, and without that I'm unable to find the free space on the SD card.
