### ISSUE TITLE
Helper refuses to work

### ISSUE THREAD

**Issue by canary-gh** [mondul/HiyaCFW-Helper#94]
When I try to use the helper it gave me the No$GBA header not found, so I fixed it. Then, this happened:

> Opening HiyaCFW Helper...
Initializing GUI...
Searching for 7-Zip in the Windows registry...
TWLTool v1.6.1
  by WulfyStylez
  Special thanks to CaitSith2
>
>reading consoleid/CID from nocashinfo block
MBR verification failed! Make sure your CID and consoleID are correct.
>
>ERROR: 2581100596102008.img
Can not open the file as archive
>
>[WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software
Exception in thread Thread-7:
Traceback (most recent call last):
  File "HiyaCFW_Helper.py", line 592, in extract_nand
  File "subprocess.py", line 800, in __init__
  File "subprocess.py", line 1207, in _execute_child
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "HiyaCFW_Helper.py", line 605, in extract_nand
NameError: name 'exe' is not defined

Any fixes?

**Comment by mondul** [comment]
Please re-dump your NAND using [Zoogie's dumpTool](https://github.com/zoogie/dumpTool/releases). Not a helper's issue, closing ticket.
