### ISSUE TITLE
Can't get hiyaCFW_helper to run on pc

### ISSUE THREAD

**Issue by zozoxo12** [mondul/HiyaCFW-Helper#95]
Okay so I'm trying to Homebrew my DSi and I've been following tech Jack's guide on how to do it. I downloaded everything I needed and made a nand bin. My SD card is 2gb or less, I have 7zip installed on my PC but still every time I try to open it with 7zip either nothing happens or it tries to get me to reinstall 7zip over and over. I'm so confused and frustrated 😂

**Comment by Kodtiz3D** [comment]
Late response but video guides by nature can be outdated, misinformative and thusly dangerous for the console. I'd use a trusted written guide such as [dsi.cfw.guide](https://dsi.cfw.guide). Also, you don't open the Helper with 7-Zip, you just run the `.exe` like any other program. Can you provide screenshots of the error windows? Both the terminal looking window and the Helper log window. Ensure you are installing 7-Zip 19.00 for your correct Windows version. That if you have a 64-bit install of Windows, to get the 64-bit/x86_64 version of 7-Zip.

**Comment by Jax45321** [comment]
every time I try to install the helper windows flagged it as a virus

**Comment by Epicpkmn11** [comment]
> every time I try to install the helper windows flagged it as a virus

That's normal because its made by PyInstaller so most anitivirus programs auto flag it as a virus, you'll need to temporarily disable your antivirus or tell it to allow this

**Comment by CaptainCrumb999RobloxYT** [comment]
Don't do any Tech James tutorials, as these get outdated quickly.
Instead, use [dsi.cfw.guide](dsi.cfw.guide)
