### ISSUE TITLE
File contains a Trojan Java Script/CoinHive

### ISSUE THREAD

**Issue by PhilantroPast** [mondul/HiyaCFW-Helper#97]
need this file to be cleaned. 

Trojan:Win32/Generic!rfn/Trojan:JS/CoinHive

5/3/2020 2:01 PM (PST)
![Screenshot](https://user-images.githubusercontent.com/64753520/80925836-f9b7fb00-8d47-11ea-82fc-0847d9116630.jpg)

**Comment by lpalmer97** [comment]
This is located in both the python 3 code and the .exe that are in the latest release.

**Comment by mondul** [comment]
Removed non-helper binaries from release. Closing ticket.
