### ISSUE TITLE
Trojans in my [archive file]!

### ISSUE THREAD

**Issue by AnimeKato** [mondul/HiyaCFW-Helper#99]
The .zip file containing the Windows ver. of hiyaCFWHelper is infected with "Trojan:Win23\Generic!rfn"

![image](https://user-images.githubusercontent.com/59742875/82151650-678a1980-9854-11ea-95e3-a680b2c07c04.png)

![image](https://user-images.githubusercontent.com/59742875/82151660-6fe25480-9854-11ea-80fd-7f20f791f2f6.png)

**Comment by bainchild** [comment]
i got one also but its different
![Capture](https://user-images.githubusercontent.com/55368789/82466829-7c4df380-9a86-11ea-8726-05e2de21ed8b.PNG)

**Comment by Santabomber** [comment]
> i got one also but its different
> ![Capture](https://user-images.githubusercontent.com/55368789/82466829-7c4df380-9a86-11ea-8726-05e2de21ed8b.PNG)

I got this warning too.. :( Whats up with that?

**Comment by AnimeKato** [comment]
> > i got one also but its different
> > ![Capture](https://user-images.githubusercontent.com/55368789/82466829-7c4df380-9a86-11ea-8726-05e2de21ed8b.PNG)


> I got this warning too.. :( Whats up with that?

i have no idea... suspicious much?

**Comment by SubsonicBeatz154** [comment]
It's a false-positive. The way the application is packaged is similar to how most viruses are, so it makes the antivirus assume it's a virus. Just add it as an exception in your antivirus software.

**Comment by Santabomber** [comment]
> It's a false-positive. The way the application is packaged is similar to how most viruses are, so it makes the antivirus assume it's a virus. Just add it as an exception in your antivirus software.

Now why would it be packed similarly to other virusfiles? Wouldn't that be easy to change? A lot of scene software is reported to have "false" positives.. I just find that a bit weird.

**Comment by mondul** [comment]
Removed non-helper binaries from release. Closing ticket.
